services:
  postgres:
    build: 
      context: ./postgres
      dockerfile: Dockerfile
    env_file:
      - ./postgres/postgres.env 
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres/init-scripts:/docker-entrypoint-initdb.d  
    networks:
      - DB-metrik-test

  postgres_exporter:
    image: docker.io/prometheuscommunity/postgres-exporter
    env_file:
      - ./postgres_exporter/postgres_exporter.env 
    depends_on:
      - postgres
    ports:
      - "9187:9187"  # for Prometheus
    networks:
      - DB-metrik-test

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml  
    ports:
      - "9090:9090"
    depends_on:
      - postgres_exporter
    networks:
      - DB-metrik-test
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    env_file:
      - ./grafana/grafana.env
    networks:
      - DB-metrik-test
    
volumes:
  postgres_data:
  grafana_data:
  prometheus_data:

networks:
  DB-metrik-test: