FROM postgres:16

# For insert simulation
# RUN apt-get update &&  \ 
#   apt-get -y install postgresql-16-cron && \ 
#   apt-get clean \ 
#   && rm -rf /var/lib/apt/lists/*
#CMD ["postgres", "-c", "shared_preload_libraries=pg_cron"]

CMD ["postgres"]